"""add course_goals

Revision ID: 246f4ad9a700
Revises: b5610318f8e6
Create Date: 2026-08-20 22:34:50.553056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246f4ad9a700'
down_revision: Union[str, Sequence[str], None] = 'b5610318f8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if 'course_goals' in sa.inspect(op.get_bind()).get_table_names():
        return  # already created by create_all() at app startup
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('target_skills', sa.JSON(), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=False),
    sa.Column('target_mastery', sa.Integer(), nullable=False),
    sa.Column('target_exam_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if 'course_goals' not in sa.inspect(op.get_bind()).get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_goals')
    # ### end Alembic commands ###
