"""init

Revision ID: ab3badd360aa
Revises: 
Create Date: 2026-06-23 13:00:46.436677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3badd360aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # No-op: tables are created by migration 001 which runs in parallel.
    # This migration branch exists for legacy databases that were initialized
    # with this revision before the numbered migration chain was added.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('test_results')
    op.drop_table('students')
    op.drop_table('questions')
    op.drop_table('courses')
    # ### end Alembic commands ###
