"""init

Revision ID: ab3badd360aa
Revises: 
Create Date: 2026-06-23 13:00:46.436677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3badd360aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'READING', 'COMPREHENSION', name='subject'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('grade_range', sa.String(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('image_emoji', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'READING', 'COMPREHENSION', name='subject'), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MULTIPLE_CHOICE', 'FILL_IN', 'ORDERING', 'MATCHING', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('pairs', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('subject', sa.Enum('MATH', 'READING', 'COMPREHENSION', name='subject'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade_equivalent', sa.Integer(), nullable=False),
    sa.Column('percentile', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('skill_breakdown', sa.JSON(), nullable=False),
    sa.Column('mastery_level', sa.Enum('BEGINNER', 'DEVELOPING', 'PROFICIENT', 'ADVANCED', name='masterylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_result_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('test_results')
    op.drop_table('students')
    op.drop_table('questions')
    op.drop_table('courses')
    # ### end Alembic commands ###
