"""sync schema with models

Revision ID: b5610318f8e6
Revises: 7c3a91be04d2
Create Date: 2026-08-20 10:29:27.131539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5610318f8e6'
down_revision: Union[str, Sequence[str], None] = '7c3a91be04d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Production's tables were created by Base.metadata.create_all() at app startup,
    # not by this chain, so they already exist -- while the columns added to already
    # existing tables are still missing. Guard every step so this runs correctly both
    # on a fresh alembic-only database and on one create_all() has already touched.
    insp = sa.inspect(op.get_bind())
    tables = set(insp.get_table_names())

    def cols(t):
        return {c['name'] for c in insp.get_columns(t)} if t in tables else set()

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if 'exam_blueprints' not in tables:
        op.create_table('exam_blueprints',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('exam_type', sa.Enum('SAT', 'ACT', 'AP', 'SECTION_QUIZ', name='examtype'), nullable=False),
        sa.Column('subject', sa.Enum('MATH', 'ENGLISH_LANGUAGE_ARTS', 'SCIENCE', 'SOCIAL_STUDIES', 'WORLD_LANGUAGES', 'TEST_PREP', 'COLLEGE_READINESS', name='subject'), nullable=True),
        sa.Column('section', sa.String(), nullable=True),
        sa.Column('question_count', sa.Integer(), nullable=False),
        sa.Column('time_limit_sec', sa.Integer(), nullable=False),
        sa.Column('grade_level', sa.Integer(), nullable=True),
        sa.Column('skill_weights', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'live_sessions' not in tables:
        op.create_table('live_sessions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('course_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('starts_at', sa.DateTime(), nullable=False),
        sa.Column('duration_min', sa.Integer(), nullable=False),
        sa.Column('meeting_url', sa.String(length=500), nullable=True),
        sa.Column('recording_url', sa.String(length=500), nullable=True),
        sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'ENDED', 'CANCELLED', name='livestatus'), nullable=False),
        sa.Column('max_students', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'subscriptions' not in tables:
        op.create_table('subscriptions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
        sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
        sa.Column('plan', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('current_period_end', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stripe_subscription_id')
        )
    if 'chat_sessions' not in tables:
        op.create_table('chat_sessions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('subject', sa.Enum('MATH', 'ENGLISH_LANGUAGE_ARTS', 'SCIENCE', 'SOCIAL_STUDIES', 'WORLD_LANGUAGES', 'TEST_PREP', 'COLLEGE_READINESS', name='subject'), nullable=True),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'diagnostic_results' not in tables:
        op.create_table('diagnostic_results',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('subject', sa.Enum('MATH', 'ENGLISH_LANGUAGE_ARTS', 'SCIENCE', 'SOCIAL_STUDIES', 'WORLD_LANGUAGES', 'TEST_PREP', 'COLLEGE_READINESS', name='subject'), nullable=False),
        sa.Column('grade_level_equivalent', sa.Integer(), nullable=False),
        sa.Column('skill_gaps', sa.JSON(), nullable=False),
        sa.Column('recommended_courses', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'forum_posts' not in tables:
        op.create_table('forum_posts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('course_id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('tags', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'personalized_courses' not in tables:
        op.create_table('personalized_courses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('base_course_id', sa.String(), nullable=False),
        sa.Column('unit_ids', sa.JSON(), nullable=False),
        sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ABANDONED', name='personalizedcoursestatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['base_course_id'], ['courses.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'base_course_id')
        )
    if 'study_plans' not in tables:
        op.create_table('study_plans',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('target_exam', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'writing_submissions' not in tables:
        op.create_table('writing_submissions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('essay_text', sa.Text(), nullable=False),
        sa.Column('ai_feedback', sa.JSON(), nullable=True),
        sa.Column('human_grade', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'chat_messages' not in tables:
        op.create_table('chat_messages',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'study_plan_items' not in tables:
        op.create_table('study_plan_items',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('study_plan_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # A rename: the model maps attribute question_type onto column 'type'.
    # Autogenerate's drop+add would discard the column's data.
    if 'question_type' in cols('final_exams'):
        op.alter_column('final_exams', 'question_type', new_column_name='type')
    if 'source_test_id' not in cols('questions'):
        op.add_column('questions', sa.Column('source_test_id', sa.String(), nullable=True))
    if 'exam_type' not in cols('test_results'):
        op.add_column('test_results', sa.Column('exam_type', sa.Enum('SAT', 'ACT', 'AP', 'SECTION_QUIZ', name='examtype'), nullable=True))
    if 'timed' not in cols('test_results'):
        op.add_column('test_results', sa.Column('timed', sa.Boolean(), nullable=False, server_default=sa.false()))
    if 'time_limit_sec' not in cols('test_results'):
        op.add_column('test_results', sa.Column('time_limit_sec', sa.Integer(), nullable=True))
    if 'section' not in cols('test_results'):
        op.add_column('test_results', sa.Column('section', sa.String(), nullable=True))
    if 'name' not in cols('users'):
        op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('test_results', 'section')
    op.drop_column('test_results', 'time_limit_sec')
    op.drop_column('test_results', 'timed')
    op.drop_column('test_results', 'exam_type')
    op.drop_column('questions', 'source_test_id')
    op.create_index(op.f('ix_lesson_questions_question_id'), 'lesson_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_lesson_questions_lesson_id'), 'lesson_questions', ['lesson_id'], unique=False)
    op.alter_column('final_exams', 'type', new_column_name='question_type')
    op.drop_table('study_plan_items')
    op.drop_table('chat_messages')
    op.drop_table('writing_submissions')
    op.drop_table('study_plans')
    op.drop_table('personalized_courses')
    op.drop_table('forum_posts')
    op.drop_table('diagnostic_results')
    op.drop_table('chat_sessions')
    op.drop_table('subscriptions')
    op.drop_table('live_sessions')
    # ix_lesson_questions_* are intentionally left in place: not declared on the
    # model, but they index the join table the SAT course seed fills.
    op.drop_table('exam_blueprints')
    # ### end Alembic commands ###
